"""Add onboarding columns to User

Revision ID: 4edba7c0e4b6
Revises: 4ada60e5f44a
Create Date: 2026-04-24 21:12:23.367870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4edba7c0e4b6'
down_revision: Union[str, Sequence[str], None] = '4ada60e5f44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birth_time', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'location')
    op.drop_column('users', 'birth_time')
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###
